import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Code2, FileHeart, GitPullRequest, Heart, MessageSquare, ShieldCheck } from "lucide-react";
import { BrandMark, GitHubIcon } from "@/components/brand";
import { ArrowLink, Eyebrow, Reveal } from "@/components/ui";
import { CallToAction } from "@/components/cta";
import { REPO, SOURCE } from "@/lib/site";

export const metadata: Metadata = { title: "Open source", description: "Built in the open. Explore the MIT-licensed NothingDNS project, contribute code, improve documentation, and help shape a better DNS server.", alternates: { canonical: "/open-source" } };

export default function OpenSourcePage() {
  return <><section className="container page-hero open-source-hero"><Reveal><Eyebrow>OPEN CODE. OPEN POSSIBILITIES.</Eyebrow><h1>Good infrastructure<br />belongs to <span className="hero-serif">everyone.</span></h1><p>DNS is a foundation of the internet.<br />We think you should be able to look under the hood.</p><div className="button-row"><a href={REPO} className="button" target="_blank" rel="noopener noreferrer"><GitHubIcon />Explore the repository<ArrowUpRight size={16} /></a><a href={`${SOURCE}/CONTRIBUTING.md`} className="button button-secondary" target="_blank" rel="noopener noreferrer">Become a contributor<ArrowUpRight size={16} /></a></div></Reveal><div className="open-source-art" aria-hidden="true"><span className="mono source-art-label">MADE TO BE OPEN</span><div className="source-orbit orbit-one" /><div className="source-orbit orbit-two" /><div className="source-orbit orbit-three" /><BrandMark /><span className="source-orbit-dot" /><span className="mono source-art-bottom">FORK IT. BUILD IT. MAKE IT YOURS.</span></div></section>
    <section className="container manifesto"><Reveal><span className="mono manifesto-label">THE IDEA IS SIMPLE</span><h2>Your DNS shouldn’t come with<br />a permission slip.</h2><p>NothingDNS is a self-contained DNS server written in Go. Authoritative DNS, recursive resolution, encrypted transports, and management live in one connected project. The code is there for you to read, run, and improve.</p><div className="manifesto-values"><span><Code2 size={19} />Source you can inspect</span><span><ShieldCheck size={19} />Infrastructure you control</span><span><Heart size={19} />Freedom to make it yours</span></div></Reveal></section>
    <section className="container section"><Reveal className="section-heading"><div><Eyebrow number="01">BUILD SOMETHING THAT MATTERS</Eyebrow><h2>There’s room<br /><span className="muted">for your contribution.</span></h2></div><p>Great software gets better with more perspectives.<br />Bring a fix, a question, or a clearer explanation.</p></Reveal><div className="contribution-grid">{[{ icon: GitPullRequest, title: "Make the code better.", text: "Fix a bug, improve a protocol implementation, or help refine the dashboard. Start with the contribution guide.", label: "Contribution guide", href: `${SOURCE}/CONTRIBUTING.md`, number: "01" }, { icon: FileHeart, title: "Make it make sense.", text: "A good example or a clearer guide can be as valuable as a feature. Help the next person find their footing.", label: "Explore the documentation", href: `${SOURCE}/docs/README.md`, number: "02" }, { icon: MessageSquare, title: "Bring your perspective.", text: "Found something unexpected? Open an issue with the details, your environment, and a way to reproduce it.", label: "Open an issue", href: `${REPO}/issues`, number: "03" }].map(({ icon: Icon, title, text, label, href, number }, i) => <Reveal className="contribution-card" key={title} delay={i * 0.07}><div><Icon size={26} /><span className="mono">{number}</span></div><h3>{title}</h3><p>{text}</p><ArrowLink href={href} external>{label}</ArrowLink></Reveal>)}</div></section>
    <section className="container section license-section"><Reveal className="license-panel"><div className="license-mark" aria-hidden="true">MIT<span>THREE LETTERS.<br />A LOT OF FREEDOM.</span></div><div><Eyebrow>OPEN BY DEFAULT</Eyebrow><h2>Use it. Change it.<br />Build on it.</h2><p>NothingDNS is released under the MIT License. Use, modify, and distribute it under the terms in the repository. Keep the copyright and license notice with your copies.</p><ArrowLink href={`${SOURCE}/LICENSE`} external>Read the license</ArrowLink></div></Reveal></section><section className="container source-resources"><div><GitHubIcon size={24} /><h3>Follow the project.</h3><p>Releases, source code, and project updates live on GitHub.</p></div><a href={`${REPO}/releases`} target="_blank" rel="noopener noreferrer">Browse releases<ArrowUpRight size={18} /></a><Link href="/docs">Start building<ArrowUpRight size={18} /></Link></section><CallToAction /></>;
}
